version: '2'
services:
  client1:
    build: ../docker/image
    cap_add:
      - NET_ADMIN
    volumes:
      - ./neo:/neo
      - ../script/client/up.sh:/up.sh
      - ../script/client/down.sh:/down.sh
    networks:
      - net1
    environment:
      - GODEBUG=netdns=cgo+1
    command: /neo -key="psk" -server="server:9606"
  client2:
    build: ../docker/image
    cap_add:
      - NET_ADMIN
    volumes:
      - ./neo:/neo
      - ../script/client/up.sh:/up.sh
      - ../script/client/down.sh:/down.sh
    networks:
      - net1
    environment:
      - GODEBUG=netdns=cgo+1
    command: /neo -key="psk" -server="server:9606"
  server:
    build: ../docker/image
    cap_add:
      - NET_ADMIN
    volumes:
      - ./neo:/neo
      - ../script/server/up.sh:/up.sh
      - ../script/server/down.sh:/down.sh
    networks:
      - net1
      - net2
    command: /neo -key="psk" -listen=":9606"
  target:
    build: ../docker/image
    networks:
      - net2
networks:
  net1:
    driver: bridge
  net2:
    driver: bridge
